### ISSUE TITLE
code does not run on arduino due

### ISSUE THREAD

**Issue by skywo1f** [SuperDroidRobots/Encoder-Buffer-Library#1]
code worked fine on arduino nano. On the due, i click upload, no errors occur, but then i don't get any messages from the due, almost like it is freezing on an earlier step.

**Comment by sdrbrent** [comment]
We've never tested this code on a Due and haven't really used a Due before. It's pretty different from other Arduinos since it uses an ARM and runs at 3.3V instead of 5V.

From what I've read the only SPI pins are on the ICSP header. Do you have the Encoder Buffer Board's SPI pins connected to the ICSP SPI pins?

And can you confirm that you are able to get Serial.println() messages with your setup?

**Comment by skywo1f** [comment]
yes, I tried using the 2x3 ICSP header and I see serial messages when the encoder library is not initialized. I could see this being an issue of the due spi needing 3.3v vs the encoder spi being 5v

**Comment by sdrbrent** [comment]
Yeah maybe you can try testing with a level shifting board for the SPI and CS pins.  It's weird though that SPI is locking up the code. AFAIK the SPI library isn't blocking, though I do see this happen with I2C. Do you get printouts if the Encoder Buffer Board is disconnected?
